location = "local-1"
server_id = 1
read_ratio = 0
local_deployment = true
# kill_signal_sec = 5
scheduled_start_utc_ms = 0
use_metronome = 2
req_batch_size = 200
interval_ms = 100 
iterations = 600
storage_duration_micros = 1000
nodes = [1, 2, 3]