location = "local-1"
server_id = 1
server_address = "127.0.0.1:8001"
summary_only = false
summary_filename = "./logs/client-1.json"
output_filename = "./logs/client-1.csv"

[request_mode_config]
request_mode_config_type = "ClosedLoop"
request_mode_config_value = 20

[end_condition]
end_condition_type = "ResponsesCollected"
end_condition_value = 1000
