location = "local-1"
server_id = 1
read_ratio = 0.25
local_deployment = true
# kill_signal_sec = 5
scheduled_start_utc_ms = SCHEDULE

[[request_rate_intervals]]
duration_sec = 10
requests_per_sec = 1

[[request_rate_intervals]]
duration_sec = 5
requests_per_sec = 10

