location = "local-1"
server_id = 1
read_ratio = 0
local_deployment = true
# kill_signal_sec = 5
scheduled_start_utc_ms = 0
use_metronome = 0
req_batch_size = 1
interval_ms = 6 
iterations = 10000
storage_duration_micros = 0
nodes = [1, 2, 3]