cluster_name = "local-cluster"
location = "local-1"
server_id = 1
local_deployment = true
total_requests = 300
num_parallel_requests = 30
summary_filepath = "../benchmarks/logs/local-experiments/client-1.json"
debug_filepath = "../benchmarks/logs/local-experiments/client-1.csv"
