cluster_name = "local-cluster"
location = "local-1"
server_id = 1
local_deployment = true
num_parallel_requests = 100
summary_filename = "../benchmarks/logs/local-experiments/client-1.json"
output_filename = "../benchmarks/logs/local-experiments/client-1.csv"

[end_condition]
end_condition_type = "ResponsesCollected"
end_condition_value = 1_000_000
