nodes = [1, 2, 3, 4, 5]
node_addrs = ["127.0.0.1:8001", "127.0.0.1:8002", "127.0.0.1:8003", "127.0.0.1:8004", "127.0.0.1:8005"]
initial_leader = 1
#worksteal_ms = 100
#straggler = 3
# metronome_quorum_size = 4

metronome_config = "RoundRobin2"

[persist_config]
persist_type = "File"
persist_value = 256

[batch_config]
batch_type = "Every"
batch_value = 15
