
x-common-variables: &common-variables
  RUST_LOG: "debug"

services:
  s1:
    image: omnipaxos-server
    build:
      context: ./..
      dockerfile: omnipaxos_server/Dockerfile
    container_name: s1
    command: ["1", "true"]
    environment:
      <<: *common-variables
    ports:
      - "8001:8001"
  s2:
    image: omnipaxos-server
    container_name: s2
    command: ["2", "true"]
    environment:
      <<: *common-variables
    ports:
      - "8002:8002"
  s3:
    image: omnipaxos-server
    container_name: s3
    command: ["3", "true"]
    environment:
      <<: *common-variables
    ports:
      - "8003:8003"
