
x-common-variables: &common-variables
  RUST_LOG: "debug"
  LOCAL: "true"

services:
  s1:
    image: omnipaxos-server
    build:
      context: ./..
      dockerfile: omnipaxos_server/Dockerfile
    container_name: s1
    environment:
      <<: *common-variables
      PID: 1
    ports:
      - "8001:8001"
  s2:
    image: omnipaxos-server
    container_name: s2
    environment:
      <<: *common-variables
      PID: 2
    ports:
      - "8002:8002"
  s3:
    image: omnipaxos-server
    container_name: s3
    environment:
      <<: *common-variables
      PID: 3
    ports:
      - "8003:8003"
