cluster_name = "local-cluster"
location = "local-5"
initial_leader = 1
local_deployment = true
instrumentation = true
debug_filepath = "../benchmarks/logs/local-experiments/server-5.csv"

[persist_config]
persist_type = "Opportunistic"
#persist_value = 10

[delay_config]
delay_type = "File"
delay_value = 1024

[cluster_config]
configuration_id = 1
nodes = [1, 2, 3, 4, 5]
use_metronome = 0
#metronome_quorum_size = 3
#flexible_quorum = { read_quorum_size = 3, write_quorum_size = 3}

[server_config]
pid = 5
election_tick_timeout = 1
resend_message_tick_timeout = 5
flush_batch_tick_timeout = 200

