cluster_name = "local-cluster"
location = "local-4"
local_deployment = true
server_id = 4
nodes = [1, 2, 3, 4, 5]
initial_leader = 1
metronome_config = "RoundRobin"
#metronome_quorum_size = 3
instrumentation = false
debug_filename = "../benchmarks/logs/local-experiments/server-4.csv"

[persist_config]
persist_type = "Individual"
#persist_value = 100

[delay_config]
delay_type = "File"
delay_value = 0
