cluster_name = "local-cluster"
location = "local-1"
initial_leader = 1
local_deployment = true
optimize = true
optimize_threshold = 0.97
storage_duration_micros = 1000
#data_size = 256

[cluster_config]
configuration_id = 1
nodes = [1, 2, 3, 4, 5]
# 1 = shuffle but still flush tail, 2 = no tail flush
use_metronome = 2
#metronome_quorum_size = 3
#flexible_quorum = { read_quorum_size = 3, write_quorum_size = 3}

[server_config]
pid = 1
election_tick_timeout = 1
resend_message_tick_timeout = 5
batch_size = 1
flush_batch_tick_timeout = 200
