cluster_name = "local-cluster"
location = "local-5"
local_deployment = true
server_id = 5
nodes = [1, 2, 3, 4, 5]
initial_leader = 1
metronome_config = "RoundRobin2"
#metronome_quorum_size = 3
instrumentation = true
debug_filename = "../benchmarks/logs/local-experiments/server-5.csv"

[persist_config]
persist_type = "File"
persist_value = 256

[batch_config]
batch_type = "Individual"
#batch_value = 60
