[package]
name = "omnipaxos_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
env_logger = "0.10.1"
futures = "0.3.30"
log = "0.4.20"
#omnipaxos = { git = "https://github.com/haraldng/omnipaxos.git", branch = "metronome", features = ["serde", "toml_config"] }
#omnipaxos = { git = "https://github.com/kevin-harrison/omnipaxos.git", branch = "auto-quorum", features = ["serde", "toml_config"] }
omnipaxos = { path = "/Users/haraldng/code/omnipaxos/omnipaxos", features = ["serde", "toml_config", "logging"] }
#omnipaxos_storage = { git = "https://github.com/haraldng/omnipaxos.git", branch = "metronome" }
#omnipaxos_storage = { git = "https://github.com/kevin-harrison/omnipaxos.git", branch = "auto-quorum" }
omnipaxos_storage = { path = "/Users/haraldng/code/omnipaxos/omnipaxos_storage" }
common = { path = "../common" }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["cbor"] }
tokio-util = { version = "0.7.10", features = ["codec"] }
lazy_static = "1.4.0"
chrono = "0.4.34"
toml = "0.8.11"
tempfile = "3.12.0"

[[bin]]
name = "server"
path = "src/main.rs"
